<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Coding.aspx.cs" Inherits="WebMediaPortfolioTemplate.Views.Coding" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cp_pageTitle" runat="server">
    <asp:Label ID="lblPageTitle" runat="server" />

    <script src="../assets/vendors/jquery/dist/jquery.min.js"></script>
    <script src="../App_JS/template.js"></script>
    <script src="../App_JS/Setup/coding.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cp_pageDesc" runat="server">
    <asp:Label ID="lblPageDesc" runat="server" />
    <br /> <br />
    <asp:DropDownList ID="ddlCodingType" CssClass="form-control" AppendDataBoundItems="true" AutoPostBack="true" runat="server" OnSelectedIndexChanged="ddlCodingType_SelectedIndexChanged">
        <asp:ListItem Text="Please select a category" />
    </asp:DropDownList>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cp_content" runat="server">
    <div class="x_panel">
        <div class="x_title">
            <h2>
                <asp:Label ID="lblPageTitle_sub" runat="server" />
                <button runat="server" onclick="showModal(0,true);" id="btnAdd" type="button" class="btn btn-warning">Add New</button>
            </h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            <p>
                <asp:Label ID="lblPageDesc_sub" runat="server" />
            </p>

            <!-- start list -->
            <asp:GridView ShowHeaderWhenEmpty="true" class="table table-striped table-bordered" ID="GridView1" runat="server" AutoGenerateDeleteButton="false" OnRowCommand="GridView1_RowCommand" OnRowDataBound="GridView1_RowDataBound" AutoGenerateColumns="false">
                <Columns>
                    <asp:BoundField Visible="false" DataField="Coding_Id" HeaderText="Coding Id" />
                    <asp:BoundField Visible="false" DataField="CodingType_Id" HeaderText="Coding Type Id" />
                    <asp:TemplateField HeaderText="Coding Description" ItemStyle-HorizontalAlign="Center">
                        <ItemTemplate>
                            <a href='#' onclick="showModal('<%# Eval("CODING_ID").ToString() %>',false)"><%# Eval("Coding_Description")%></a> </td>

                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField ItemStyle-HorizontalAlign="Center">
                        <ItemTemplate>
                            <img width="200" height="100" src="<%# Eval("URL")%>">
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:BoundField Visible="false" DataField="Valid_From" DataFormatString="{0:MM-dd-yyyy}" HeaderText="Valid From" />
                    <asp:BoundField Visible="false" DataField="Valid_To" DataFormatString="{0:MM-dd-yyyy}" HeaderText="Valid To" />

                    <asp:TemplateField ItemStyle-HorizontalAlign="Center">
                        <ItemTemplate>
                            <asp:LinkButton CssClass="btn btn-primary btn-sm" Text="Edit" runat="server"
                                PostBackUrl='<%# string.Format("~/Views/Content.aspx?Id={0}", Eval("Coding_Id")) %>' />
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField ItemStyle-HorizontalAlign="Center">
                        <ItemTemplate>
                            <asp:LinkButton OnClientClick='if (!confirm("Are you sure you want to delete this record?")) return false;' CommandArgument='<%# Eval("Coding_Id") %>' CommandName="Del" runat="server">
                         <img src="/Assets/images/delete.png" alt="edit" /><br />Delete
                            </asp:LinkButton>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <!-- end  list -->
        </div>
    </div>

    <div id="modalRec" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Record Details</h4>
                </div>
                <div class="modal-body">
                    <div id="modalContent">
                        <table id="tblForm" class="table table-striped table-bordered">
                            <tr>
                                <td>Description</td>
                                <td>
                                    <asp:TextBox Width="400px" name="desc" runat="server" ClientIDMode="Static" ID="txtDesc" class="form-control" />
                                </td>
                                <td>File 
                                        <asp:FileUpload ID="fileUpload" runat="server" />
                                </td>
                            </tr>
                        </table>
                        <div id="divStamp">
                            <kokahUC:ModalStamp ID="modalStamp" runat="server" />
                        </div>
                    </div>
                </div>

                <div class="modal-footer">

                    <div class="col-md-1 col-sm-1 col-xs-1">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                    <div class="col-md-1 col-sm-1 col-xs-1">
                        <button class="btn btn-danger" type="button" id="btnClear" onclick="clearModal(document.getElementById('modalRec'),true);">Clear</button>
                    </div>

                    <div style="text-align: right;" class="col-md-10 col-sm-10 col-xs-10">
                        <asp:Button Text="Save" runat="server" ID="btnSave" OnCommand="btnSave_Command" CommandArgument="save" class="btn btn-default" OnClientClick='return validate();' />
                        <asp:HiddenField ID="hdRecId" ClientIDMode="Static" runat="server" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
